---
kind: pipeline
name: nixos-tests

steps:
- name: test
  image: busybox
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
  volumes:
    - name: nixstore
      path: /nix
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  commands:
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz -A sops-install-secrets.tests
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-20.09.tar.gz -A sops-install-secrets.tests
volumes:
- name: nixstore
  host:
    path: /nix
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl
---
kind: signature
hmac: 5bb657faca0ecd18576534f7e486511d6f698595cc244d9617e660ef2ddb678d

...
