name: "Flake test"
on:
  pull_request:
  schedule:
    - cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: mic92
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: List flake structure
      run: nix flake show
    - name: Run flake check (flake)
      run: nix flake check -L
